name: Code Quality

on:
  push:
    branches: ["main", "wicaksu"]
  pull_request:
    branches: ["main", "wicaksu"]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Install NPM Dependencies
        run: npm install
      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 app/
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
      - name: Run ESLint
        run: npm run lint
